#  飞书
APP_ID: cli_axxx
APP_SECRET: xxx
APP_ENCRYPT_KEY: xxx
APP_VERIFICATION_TOKEN: xxx
# 请确保和飞书应用管理平台中的设置一致
BOT_NAME: 飞书-文心一言
# Ernie 配置信息
ClientID: xxx
ClientSecret: xxx
# 服务器配置
HTTP_PORT: 9000
HTTPS_PORT: 9001
USE_HTTPS: false
CERT_FILE: cert.pem
KEY_FILE: key.pem





# 百度
WENXIN_CLIENT_ID: xxx
WENXIN_CLIENT_SECRET: xxx
